module.exports.UPDATE = 'UPDATE';
module.exports.CONNECTION_STATE='CONNECTION_STATE';
module.exports.REPLACE_IN_QUEUE = 'REPLACE_IN_QUEUE';
module.exports.ADD_TO_QUEUE = 'ADD_TO_QUEUE';
module.exports.REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';
module.exports.ADD_NOTIFICATION = 'ADD_NOTIFICATION';
module.exports.DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
